{% set SRA_TOOLS_VERSION = "2.7.0" %}

package:
  name: sra-tools
  version: {{ SRA_TOOLS_VERSION }}

build:
  number: 0

source:
  fn: sra-tools-{{ SRA_TOOLS_VERSION }}.tar.gz
  url: https://github.com/ncbi/sra-tools/archive/{{ SRA_TOOLS_VERSION }}.tar.gz
  sha256: 274cd6c4a228c351b5e72eecf382d73d5cccde7d852940af68877883d7e1ea8e

  notes: "This package includes ncbi-vdb and ngs-sdk. After installation, you should run the configuration tool: ./vdb-config -i. This tool will setup your download/cache area for downloaded files and references."

requirements:
  build:
    - gcc # [not osx]
    - llvm # [osx]
  run:
    #

about:
  home: https://github.com/ncbi/sra-tools
  license: Public Domain
  summary: The SRA Toolkit and SDK from NCBI is a collection of tools and
           libraries for using data in the INSDC Sequence Read Archives.
test:
  commands:
    # "Frequently Used Tools"
    - fastq-dump --help > /dev/null
    - prefetch --help > /dev/null
    - sam-dump --help > /dev/null
    - sra-pileup --help > /dev/null
    - vdb-config --help > /dev/null
    - vdb-decrypt --help > /dev/null
